// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeW6WD41AhbfbgueVNTFnPOcOeVnYvbnI',
    appId: '1:235037268342:web:38a2901f727575de1a0257',
    messagingSenderId: '235037268342',
    projectId: 'vaultkey-616bf',
    authDomain: 'vaultkey-616bf.firebaseapp.com',
    storageBucket: 'vaultkey-616bf.firebasestorage.app',
    measurementId: 'G-7C9HDS2YSR',
  );

  static const FirebaseOptions android = FirebaseOptions(apiKey: 'AIzaSyC3ufFT203aVwkLZwzW0cJzjI4Ohj-CwIY', appId: '1:235037268342:android:2d4206e052c2966f1a0257', messagingSenderId: '235037268342', projectId: 'vaultkey-616bf', storageBucket: 'vaultkey-616bf.firebasestorage.app');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPvRjQB3WqA-v7ftEjehjVXlOkBBXxo4',
    appId: '1:235037268342:ios:10c964e3efd025201a0257',
    messagingSenderId: '235037268342',
    projectId: 'vaultkey-616bf',
    storageBucket: 'vaultkey-616bf.firebasestorage.app',
    iosClientId: '235037268342-l17lsvncsboorj0ah3frvj5eka4iiehl.apps.googleusercontent.com',
    iosBundleId: 'com.auth.vaultkey',
  );
}

/// Supabase configuration options
/// Used as secondary/redundant backend for VaultKey
///
/// Features:
/// - Secondary/redundant data storage
/// - Alternative backup storage option
/// - Additional analytics data storage
/// - Fallback authentication provider (if needed)
class SupabaseOptions {
  /// Supabase project URL
  static const String supabaseUrl = 'https://ejigscnhdcphprouthub.supabase.co';

  /// Supabase public key (for client-side operations)
  static const String supabasePublicKey = 'sb_publishable_Y99oOKJWyM2whk1WailpFw_HMrLeOA5';

  /// Supabase anonymous key (for unauthenticated access)
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaWdzY25oZGNwaHByb3V0aHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1OTIyNDgsImV4cCI6MjA4MjE2ODI0OH0.JSv_VTIk0v9QZp7KrjwXf0xr2C0fx-w_5QunYAR92co';

  /// Get current platform-specific options
  /// For now, Supabase uses the same configuration for all platforms
  static SupabaseConfig get currentPlatform => const SupabaseConfig(url: supabaseUrl, anonKey: supabaseAnonKey);
}

/// Supabase configuration data class
class SupabaseConfig {
  final String url;
  final String anonKey;

  const SupabaseConfig({required this.url, required this.anonKey});
}
