// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeW6WD41AhbfbgueVNTFnPOcOeVnYvbnI',
    appId: '1:235037268342:web:b842c958822bf14b1a0257',
    messagingSenderId: '235037268342',
    projectId: 'vaultkey-616bf',
    authDomain: 'vaultkey-616bf.firebaseapp.com',
    storageBucket: 'vaultkey-616bf.firebasestorage.app',
    measurementId: 'G-Y6NFGVQC1S',
  );

  static const FirebaseOptions android = FirebaseOptions(apiKey: 'AIzaSyC3ufFT203aVwkLZwzW0cJzjI4Ohj-CwIY', appId: '1:235037268342:android:00e2c0e99515d66f1a0257', messagingSenderId: '235037268342', projectId: 'vaultkey-616bf', storageBucket: 'vaultkey-616bf.firebasestorage.app');

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLPvRjQB3WqA-v7ftEjehjVXlOkBBXxo4',
    appId: '1:235037268342:ios:d9c8e68c7cae163c1a0257',
    messagingSenderId: '235037268342',
    projectId: 'vaultkey-616bf',
    storageBucket: 'vaultkey-616bf.firebasestorage.app',
    iosBundleId: 'com.example.vaultkey',
  );
}

class SupabaseOptions {
  static const String supabaseUrl = 'https://ejigscnhdcphprouthub.supabase.co';
  static const String supabasePublicKey = "sb_publishable_Y99oOKJWyM2whk1WailpFw_HMrLeOA5";
  static const String supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqaWdzY25oZGNwaHByb3V0aHViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY1OTIyNDgsImV4cCI6MjA4MjE2ODI0OH0.JSv_VTIk0v9QZp7KrjwXf0xr2C0fx-w_5QunYAR92co";
}
